- name: Configure SELinux for services
  become: true
  vars:
    directories:
      - "/mnt/nas/share"
      - "/mnt/scratch/slskd"
      - "/mnt/scratch/transmission"
  block:
    - name: Configure SELinux context
      community.general.sefcontext:
        setype: public_content_rw_t
        path: "{{ item }}(/.*)?"
        state: present
      loop: "{{ directories }}"
      register: fcontext_changes

    - name: Restore SELinux context
      ansible.builtin.command:
        cmd: "restorecon -rF {{ item }}"
      loop: "{{ directories }}"
      when: fcontext_changes.changed
      changed_when: true

- name: Allow containers to read/write to public content
  become: true
  ansible.posix.seboolean:
    name: container_manage_public_content
    state: true
    persistent: true

- name: Allow containers to use devices
  become: true
  ansible.posix.seboolean:
    name: container_use_devices
    state: true
    persistent: true
