#!/bin/sh

TIMESTAMP_FILE="/tmp/config-perms-timestamp"

if [ ! -f "$TIMESTAMP_FILE" ]; then
    touch -d "1 hour ago" "$TIMESTAMP_FILE"
fi

chgrp -R nasusers /srv/nasusers/mimir-config

find /srv/nasusers/mimir-config -newer "$TIMESTAMP_FILE" -type d -exec chmod 770 {} \;
find /srv/nasusers/mimir-config -newer "$TIMESTAMP_FILE" -type f -executable -exec chmod 770 {} \;
find /srv/nasusers/mimir-config -newer "$TIMESTAMP_FILE" -type f ! -executable -exec chmod 660 {} \;

touch "$TIMESTAMP_FILE"
