name: 'mimir'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1500:1002
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - jellyfin_config:/config:Z
      - jellyfin_cache:/cache:Z
      - /mnt/nas/share:/media:ro,z
    devices:
      - "nvidia.com/gpu=0"
    restart: 'unless-stopped'
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 100.81.185.89:5030:5030/tcp # slskd
      - 100.81.185.89:5031:5031/tcp
      - 100.81.185.89:9091:9091/tcp # transmission
      - 51413:51413/tcp
      - 51413:51413/udp
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'sed -i "s/^\([[:space:]]*listen_port:\).*/\1 {{PORT}}/" /slskd_app/slskd.yml'
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=United States
    volumes:
      - slskd_app:/slskd_app:z
  slskd:
    image: slskd/slskd
    container_name: slskd
    user: 1500:1002
    network_mode: service:gluetun
    environment:
      - SLSKD_USERNAME=mimir
      - SLSKD_PASSWORD=${SLSKD_PASSWORD}
      - SLSKD_SLSK_USERNAME=m1m1r
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
      - SLSKD_SHARED_DIR=/share
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_DOWNLOADS_DIR=/files/downloads
      - SLSKD_INCOMPLETE_DIR=/files/incomplete
    volumes:
      - slskd_app:/app:z
      - /mnt/nas/share:/share:ro,z
      - /mnt/scratch/slskd:/files:z
    restart: always
    depends_on:
      - gluetun
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: mimir
    environment:
      - PGID=1002
      - PUID=1002
      - STGUIADDRESS=100.81.185.89:8384
    volumes:
      - syncthing_config:/var/syncthing:Z
      - /mnt/nas/share/k9:/data:z
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
  tinymediamanager:
    image: tinymediamanager/tinymediamanager:latest
    container_name: tinymediamanager
    environment:
      - USER_ID=1002
      - GROUP_ID=1002
      - ALLOW_DIRECT_VNC=true
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - PASSWORD=${TINYMEDIAMANAGER_PASSWORD}
    volumes:
      - tinymediamanager_data:/data:Z
      - /mnt/nas/share/k9/Videos/Movies:/media/movies:z
      - /mnt/nas/share/k9/Videos/TV:/media/tv_shows:z
    ports:
      - 100.81.185.89:5900:5900
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: service:gluetun
    environment:
      - PUID=1500
      - PGID=1002
      - TZ=America/Los_Angeles
    volumes:
      - transmission_config:/config:Z
      - /mnt/scratch/transmission/downloads:/downloads:z
      - /mnt/scratch/transmission/watch:/watch:z
    restart: unless-stopped
    depends_on:
      - gluetun
volumes:
  jellyfin_config:
  jellyfin_cache:
  slskd_app:
  syncthing_config:
  tinymediamanager_data:
  transmission_config:
