- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - { role: devsec.hardening.ssh_hardening, tags: ssh }
    - { role: common,    tags: common }
    - { role: tailscale, tags: tailscale }
    - { role: nvidia,    tags: nvidia }
    - { role: selinux,   tags: selinux }
    - { role: samba,     tags: samba }
    - { role: podman,    tags: podman }
    - { role: rclone,    tags: rclone }
    - { role: borg,      tags: borg }
    - { role: cron,      tags: cron }
