[nas]
comment = Nas Share
path = /mnt/nas/share
writeable = yes
browseable = yes
create mask = 644
directory mask = 755
valid users = @nasusers
force group = +nasusers
veto files = /.DS_Store/ /._.DS_Store/
delete veto files = yes

[slskd]
comment = Slskd Share
path = /mnt/scratch/slskd
writeable = yes
browseable = yes
create mask = 640
directory mask = 750
valid users = @nasusers
force group = +nasusers
veto files = /.DS_Store/ /._.DS_Store/
delete veto files = yes

[nicotine]
comment = Nicotine Share
path = /mnt/scratch/nicotine
writeable = yes
browseable = yes
create mask = 640
directory mask = 750
valid users = @nasusers
force group = +nasusers
veto files = /.DS_Store/ /._.DS_Store/
delete veto files = yes

[transmission]
comment = Torrent Downloads
path = /mnt/scratch/transmission
writeable = yes
browseable = yes
create mask = 640
directory mask = 750
valid users = @nasusers
force group = +nasusers
veto files = /.DS_Store/ /._.DS_Store/
delete veto files = yes
