- name: Add /mnt/nas/share backup to crontab
  ansible.builtin.cron:
    name: "backup /mnt/nas/share"
    minute: 0
    hour: 3
    job: "/usr/bin/rclone -v --exclude \".*{/**,}\" --min-age 3d --fast-list --max-duration 3h --cutoff-mode SOFT copy /mnt/nas/share/ MimirArchiveCrypt:"

- name: Copy backup_containers.bash
  ansible.builtin.template:
    src: "backup_containers.bash.j2"
    dest: "/usr/local/bin/backup_containers.bash"
    owner: root
    group: root
    mode: '755'

- name: Add backup_containers.bash to crontab
  ansible.builtin.cron:
    name: "backup containers"
    minute: 30
    hour: 3
    job: "/usr/local/bin/backup_containers.bash"
