- name: Enable AlmaLinux NVIDIA driver repository
  ansible.builtin.dnf:
    name:
      - almalinux-release-nvidia-driver
    update_cache: true
    state: present

- name: Install NVIDIA drivers
  ansible.builtin.dnf:
    name:
      - nvidia-open
      - nvidia-driver-cuda
    update_cache: true
    state: present

- name: Load nvidia_drm kernel module
  community.general.modprobe:
    name: nvidia_drm
    state: present

- name: Add NVIDIA Container Toolkit repository
  ansible.builtin.yum_repository:
    name: nvidia-container-toolkit
    description: NVIDIA Container Toolkit
    baseurl: "https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64"
    enabled: true
    gpgcheck: true
    gpgkey: "https://nvidia.github.io/libnvidia-container/gpgkey"
    module_hotfixes: true
    priority: 30

- name: Install NVIDIA Container Toolkit
  ansible.builtin.dnf:
    name:
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
    state: present
  notify: Restart nvidia-cdi-refresh

- name: Enable nvidia-cdi-refresh service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nvidia-cdi-refresh.service
    - nvidia-cdi-refresh.path
