- name: Retrieve GID of nasusers group
  ansible.builtin.getent:
    database: group
    key: nasusers

- name: Set fact for nasusers GID
  ansible.builtin.set_fact:
    nasusers_gid: "{{ ansible_facts.getent_group.nasusers.1 }}"

- name: Enable linger for podman
  ansible.builtin.command:
    cmd: loginctl enable-linger podman
    creates: "/var/lib/systemd/linger/podman"
  become: true

- name: Install jq
  become: true
  ansible.builtin.dnf:
    name:
      - jq
    state: present

- name: Copy get-gluetun-forwarded-port.sh
  become: true
  ansible.builtin.copy:
    src: "files/get-gluetun-forwarded-port.sh"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: '755'

- name: Copy gluetun default config
  become: true
  ansible.builtin.copy:
    src: "files/gluetun-config.toml"
    dest: "/etc/containers/systemd/users/{{ podman_uid }}"
    owner: root
    group: root
    mode: '644'

- name: Create quadlets folder for podman containers
  become: true
  ansible.builtin.file:
    path: "/etc/containers/systemd/users/{{ podman_uid }}"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Copy jellyfin quadlets
  become: true
  ansible.builtin.copy:
    src: "files/jellyfin/"
    dest: "/etc/containers/systemd/users/{{ podman_uid }}"
    owner: root
    group: root
    mode: '644'
  notify:
    - Reload podman systemd
    - Restart podman jellyfin

- name: Copy slskd quadlets
  become: true
  ansible.builtin.copy:
    src: "files/slskd/"
    dest: "/etc/containers/systemd/users/{{ podman_uid }}"
    owner: root
    group: root
    mode: '644'
  notify:
    - Configure SELinux context for gluetun config
    - Restore SELinux context for gluetun config
    - Reload podman systemd
    - Restart podman slskd

- name: Copy nicotine quadlets
  become: true
  notify:
    - Reload podman systemd
    - Restart podman nicotine
  block:
    - name: Copy nicotine files
      ansible.builtin.copy:
        src: "files/nicotine/"
        dest: "/etc/containers/systemd/users/{{ podman_uid }}"
        owner: root
        group: root
        mode: '644'

    - name: Deploy nicotine files
      ansible.builtin.template:
        src: "nicotine/nicotine-vpn-nicotine.container.j2"
        dest: "/etc/containers/systemd/users/{{ podman_uid }}/nicotine-vpn-nicotine.container"
        owner: root
        group: root
        mode: '644'

- name: Copy transmission quadlets
  become: true
  notify:
    - Reload podman systemd
    - Restart podman transmission
  block:
    - name: Copy transmission files
      ansible.builtin.copy:
        src: "files/transmission/"
        dest: "/etc/containers/systemd/users/{{ podman_uid }}"
        owner: root
        group: root
        mode: '644'

    - name: Deploy transmission files
      ansible.builtin.template:
        src: "transmission/transmission-vpn-transmission.container.j2"
        dest: "/etc/containers/systemd/users/{{ podman_uid }}/transmission-vpn-transmission.container"
        owner: root
        group: root
        mode: '644'
