- name: Retrieve GID of nasusers group
  ansible.builtin.getent:
    database: group
    key: nasusers

- name: Set fact for nasusers GID
  ansible.builtin.set_fact:
    nasusers_gid: "{{ ansible_facts.getent_group.nasusers.1 }}"

- name: Enable linger for podman
  ansible.builtin.command:
    cmd: loginctl enable-linger podman
    creates: "/var/lib/systemd/linger/podman"
  become: true

- name: Create quadlets folder for podman containers
  become: true
  ansible.builtin.file:
    path: "/etc/containers/systemd/users/{{ podman_uid }}"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Copy jellyfin quadlets
  become: true
  ansible.builtin.copy:
    src: "files/jellyfin/"
    dest: "/etc/containers/systemd/users/{{ podman_uid }}"
    owner: root
    group: root
    mode: '644'
  notify:
    - Reload podman systemd
    - Restart podman jellyfin

- name: Copy slskd quadlets
  become: true
  ansible.builtin.copy:
    src: "files/slskd/"
    dest: "/etc/containers/systemd/users/{{ podman_uid }}"
    owner: root
    group: root
    mode: '644'
  notify:
    - Configure SELinux context for slskd gluetun config
    - Restore SELinux context for slskd gluetun config
    - Reload podman systemd
    - Restart podman slskd

- name: Copy transmission quadlets
  become: true
  notify:
    - Reload podman systemd
    - Restart podman transmission
  block:
    - name: Copy transmission files
      ansible.builtin.copy:
        src: "files/transmission/"
        dest: "/etc/containers/systemd/users/{{ podman_uid }}"
        owner: root
        group: root
        mode: '644'

    - name: Deploy transmission files
      ansible.builtin.template:
        src: "transmission/transmission-vpn-transmission.container.j2"
        dest: "/etc/containers/systemd/users/{{ podman_uid }}/transmission-vpn-transmission.container"
        owner: root
        group: root
        mode: '644'

