- name: Ensure {{ borg_dir }} exists
  ansible.builtin.file:
    path: "{{ borg_dir }}"
    state: directory
    mode: 700

- name: Copy passfile to {{ borg_dir }}
  ansible.builtin.copy:
    src: "files/passfile"
    dest: "{{ borg_dir }}/passfile"
    mode: 600
    owner: root
    group: root

- name: Initialize borg repo
  ansible.builtin.command:
    cmd: >
      export BORG_REPO="{{ repo_dir }}"
      export BORG_PASSCOMMAND="cat {{ borg_dir }}/passfile"
      borg init -e repokey
  args:
    creates: "{{ repo_dir }}"
