- name: Create nasusers group
  ansible.builtin.group:
    name: nasusers
    state: present

- name: Create podman user
  become: true
  ansible.builtin.user:
    name: podman
    uid: "{{ podman_uid }}"
    shell: "/sbin/nologin"
    create_home: true
    group: podman
    groups: nasusers
    append: true
    state: present

- name: Ensure parent directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "/mnt/nas"
    - "/mnt/scratch"

- name: Create nas directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: nasusers
    mode: '770'
  loop:
    - { path: "/mnt/nas/share", owner: "root" }

- name: Create scratch directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: nasusers
    mode: '2770'
  loop:
    - { path: "/mnt/scratch/slskd",        owner: "podman" }
    - { path: "/mnt/scratch/transmission", owner: "podman" }
