- name: Reload podman systemd
  become: true
  become_user: podman
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart podman jellyfin
  become: true
  become_user: podman
  ansible.builtin.systemd:
    name: "jellyfin"
    state: restarted
    enabled: true
    scope: user

- name: Restart podman slskd
  become: true
  become_user: podman
  ansible.builtin.systemd:
    name: "slskd-vpn-pod"
    state: restarted
    enabled: true
    scope: user

- name: Restart podman transmission
  become: true
  become_user: podman
  ansible.builtin.systemd:
    name: "slskd-vpn-pod"
    state: restarted
    enabled: true
    scope: user
