- name: Reload podman systemd
  become: true
  become_user: podman
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart podman jellyfin
  become: true
  become_user: podman
  ansible.builtin.systemd:
    name: "jellyfin"
    state: restarted
    enabled: true
    scope: user

- name: Configure SELinux context for slskd gluetun config
  become: true
  community.general.sefcontext:
    setype: container_file_t
    path: "/etc/containers/systemd/users/{{ podman_uid }}/slskd-vpn-gluetun-config.toml"
    state: present
  register: fcontext_changes

- name: Restore SELinux context for slskd gluetun config
  become: true
  ansible.builtin.command:
    cmd: "restorecon -rF /etc/containers/systemd/users/{{ podman_uid }}/slskd-vpn-gluetun-config.toml"
  when: fcontext_changes.changed
  changed_when: true

- name: Restart podman slskd
  become: true
  become_user: podman
  ansible.builtin.systemd:
    name: "slskd-vpn-pod"
    state: restarted
    enabled: true
    scope: user

- name: Restart podman transmission
  become: true
  become_user: podman
  ansible.builtin.systemd:
    name: "transmission-vpn-gluetun"
    state: restarted
    enabled: true
    scope: user
